// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCyBfqxWGZUx0r5mrJBHLJ1tt_gUviW6vc',
//     appId: '1:875756146552:web:00b92ab6e14f927839028d',
//     messagingSenderId: '875756146552',
//     projectId: 'ski-30fd3',
//     authDomain: 'ski-30fd3.firebaseapp.com',
//     storageBucket: 'ski-30fd3.appspot.com',
//     measurementId: 'G-22ZRJQEYML',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCPE1MLstIV_3h6c0VVcfIjW-EMLarbX_E',
//     appId: '1:875756146552:android:a91b9c9607c9f8ec39028d',
//     messagingSenderId: '875756146552',
//     projectId: 'ski-30fd3',
//     storageBucket: 'ski-30fd3.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB29PF4zuHpOTPaaE9mMb_cgiEQg6THdkw',
//     appId: '1:875756146552:ios:5caca4c8b2647ad239028d',
//     messagingSenderId: '875756146552',
//     projectId: 'ski-30fd3',
//     storageBucket: 'ski-30fd3.appspot.com',
//     iosBundleId: 'com.example.ski',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB29PF4zuHpOTPaaE9mMb_cgiEQg6THdkw',
//     appId: '1:875756146552:ios:5caca4c8b2647ad239028d',
//     messagingSenderId: '875756146552',
//     projectId: 'ski-30fd3',
//     storageBucket: 'ski-30fd3.appspot.com',
//     iosBundleId: 'com.example.ski',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCyBfqxWGZUx0r5mrJBHLJ1tt_gUviW6vc',
//     appId: '1:875756146552:web:8134ac1bcdb15d0c39028d',
//     messagingSenderId: '875756146552',
//     projectId: 'ski-30fd3',
//     authDomain: 'ski-30fd3.firebaseapp.com',
//     storageBucket: 'ski-30fd3.appspot.com',
//     measurementId: 'G-6MSSZ78QCM',
//   );
// }
