// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCyBfqxWGZUx0r5mrJBHLJ1tt_gUviW6vc',
  //   appId: '1:875756146552:web:23472ac907259ede39028d',
  //   messagingSenderId: '875756146552',
  //   projectId: 'ski-30fd3',
  //   authDomain: 'ski-30fd3.firebaseapp.com',
  //   databaseURL: 'https://ski-30fd3-default-rtdb.firebaseio.com',
  //   storageBucket: 'ski-30fd3.appspot.com',
  //   measurementId: 'G-KQ5523GRN6',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGkDfmWM8LaiePDX2gcjCaDTIv5vRUBE',
    appId: '1:522444229973:android:76e10d5b14c472fa67f3dc',
    messagingSenderId: '522444229973',
    projectId: 'sellkaroindia-268ac',
    storageBucket: 'sellkaroindia-268ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLVhxO9ISXLB_LKWEifXo38DDV3yTLj0',
    appId: '1:522444229973:ios:fa227410684a0e8f67f3dc',
    messagingSenderId: '522444229973',
    projectId: 'sellkaroindia-268ac',
    storageBucket: 'sellkaroindia-268ac.appspot.com',
    iosBundleId: 'com.example.sellKaroIndia',
  );

}